var sampleData = [
  "Bomba de agua",
  "Climatizador",
  "bujias",
  "bujias incandescentes",
  "bujias precalentamientos cortas",
  "calentadores",
  "fiesta no arranca",
  "modelo de bujia endura d 1.8",
  "no arranca",
  "no calienta los calentadores",
  "precalentamiento",
  "tipos de bujias calentamientos",
  "Aire",
  "Bajo rpm en endeavor",
  "presion de aceite baja",
  "enciende y apaga de una vez",
  "prende y se apaga mi renault twingo",
  "estatus 2001 enciende y se apaga camina y se tironea",
  "Buenas amigo revisa la valvula PCV tal vez este abierta y pudiera ser el consumo de... Usa semisintético 15w-40 de buena calidad.",
  "bomba de agua",
  "bujias",
  "bujias carbonizadas",
  "correa de tiempo",
  "correa de tiempo original",
  "damper",
  "multiple de admision",
  "pcv",
  "pcv abierto",
  "pcv se quedo abierto",
  "refrigerante",
  "refrigerantes",
  "sensor  mao original",
  "sensor map original",
  "tornillo damper",
  "valvula pcv tal vez esta abierta",
  "varilla de aceite",
  "SE APAGA",
  "bomba de nafta fiesta",
  "bomba nafta fiesta",
  "calienta los relay fiesta",
  "fiesta lx",
  "fusible bomba de nafta",
  "fusible bomba fiesta lx",
  "fusilera fiesta gnc",
  "no llega corriente a la bomba fiesta",
  "correa de tiempo",
  "Accord",
  "Accord 2011",
  "Chevrolet Captiva",
  "agua con gasolina",
  "agua con gasolina",
  "agua y aceite",
  "agua y gasolina",
  "caja",
  "gasolina en el reservorio de agua",
  "agua y gasolina",
  "prende la luz de aceite",
  "Al meter la tercera en mi auto cuesta y hace ruidos",
  "Aceite de dirección hidraulica",
  "MO NE TRABAJA EL PILOTO AUTOMATICO",
  "NO ME TRABAJA EL TRUST CONTROL",
  "carro acelerado cuan se calienta",
  "fallas cuando la banda de tiempo se brinca",
  "se acelera",
  "sintomas cuando la banda de tiempo se brinca",
  "tren trasero",
  "Beetle 2.5",
  "Relevados 428",
  "donde queda el tapon de la caja para echarle aceite",
  "sensor cigueñal",
  "sensor de detonacion",
  "sensor golpe",
  "sensor map",
  "valvula iac",
  "cambiar motor de ford explorer",
  "se apaga",
  "se apaga renault kangoo",
  "sensor temperatura",
  "luz tablero no se apaga.",
  "no se apagan luces de tablero",
  "que es la chapa de contacto?",
  "Range Rover",
  "Captiva",
  "Mantenimiento lancer",
  "Sensor de posicion de arbol de levas a",
  "Sensor de posicion de arbol de levas",
  "catalizador optra",
  "fallas en el catalizador optra",
  "se apaga",
  "perdida de agua siena",
  "Donde queda la valvula de alta sistema",
  "Sistema A/A",
  "Emulsión de aceite con refrigerante",
  "Luz roja de tablero de kangoo 2001 no enciende",
  "Tengo problemas con la luz roja del tablero deje de parpadear y no me arranca... Es una kangoo",
  "Gasolina",
  "Chupe Aire",
  "Que aceite lleva un sonic 2016",
  "Soportes del motor",
  "turbo",
  "lubricacion",
  "porque cada vez que se calienta el aceite de mi vw golf iv empieza a sonar los taquetes",
  "rx8",
  "ltz",
  "Mala combustión",
  "Se apaga",
  "Sensor de velocidad",
  "Cómo conectar un sensor de velocidad a un optra",
  "agua",
  "motor",
  "Temporizador de precalentamiento",
  "reprogramacion tcm nissan pathfinder",
  "Compresor aire acondicionado fiat palio",
  "bota aceite al levantar el carro para cambiar un caucho",
  "no activa la bomba de gasolina",
  "variadores",
  "variadores mercedes C 200",
  "Mazda suena como diesel",
  "Electro ventilador",
  "Falla al acelerar",
  "Falla al acelerar",
  "deposito limpiaparabrisas",
  "limpiaàrabrisas",
  "limpiaparabrisas",
  "P0299",
  "balastro",
  "bujía no tiene chispa",
  "bujías no tienen chispa",
  "bujia no tiene chispa",
  "codigo de error 89",
  "motor ruido",
  "CRUCERO",
  "BATERIA",
  "BATERIA DEL 207 COMPACT",
  "NO ME ARRANCA",
  "QUE BATERIA LLEVA MI AUTO",
  "TENGO CONTACTO PERO NO ARRANCA",
  "Neutral switch",
  "anomalia anticontaminacion",
  "anomalia anticontaminacion",
  "anomalia anticontaminacion hdi",
  "accent se apaga",
  "Revoluciones",
  "codigo del esterio",
  "fiesta2012",
  "sonido al encender",
  "sonido al encender",
  "sonido al encender sonata",
  "Se apaga de la nada bora gli",
  "El motor no enciende a veces spark",
  "A que kilometraje se cambia la correa de distribución de un Jets 2.5",
  "Correa de reparticion",
  "Correa de reparticion en una jeta 2.5",
  "Distribuidor fiat uno scr",
  "Recalentamiento modulo fiat uno scr",
  "gol trend",
  "jetta tdi",
  "correa dentada de distribución",
  "distribución cómo sincronizar",
  "motor recalienta",
  "por qué recalienta un motor causas y soluciones",
  "recalentamiento del motor",
  "recalentamiento del motor causas y soluciones",
  "recalienta el motor",
  "código po717",
  "Mensaje acelere o apague",
  "Arranque",
  "Marca erroneo el velocimetro c3 2010",
  "Buenos dias amigo mi carro vw gol 2002 presenta la misma falla q el de iraima ya le hice mantenimiento completo y sigue igual... solo enfria parado o a bajas velocidades pero en carretera cuando le exijo velocidad al carro deja de enfriar... me comentaron q podria ser la valvula poa pero que este compresor que es el original no usa esa valvula y que por lo tanto ya esta dañado q opinion tu me darias?",
  "aire acondicionado",
  "grand picasso",
  "Se desprogramaron los vidrios eléctricos",
  "lo enciendo y no acelera",
  "no marca el kilometraje",
  "se acelera cuando la valvula de temperatura",
  "se acelera solo",
  "se acelera solo cuando arranca el electro",
  "sensor de electroventilador",
  "sensor de temperatura",
  "tablero",
  "valvula de ventilador",
  "valvula electro ventilador",
  "valvula de temperatura",
  "velocimetro",
  "alra",
  "bujías",
  "bujias",
  "caudalímetro",
  "check engine",
  "coolant",
  "franklinosayandescott@Gmail.con",
  "hauswagen",
  "luz",
  "oye",
  "prestamo",
  "servofrenos",
  "vibracion volante",
  "Abs",
  "Aceite",
  "Como programar mi toyota camry 1999",
  "Altima 2002 no hay chispa",
  "No hay chispa",
  "peugeot 807",
  "ACTIVACION DE ALARMA",
  "ALARMA",
  "Alarma no funciona",
  "LUCES AL ACTIVAR ALARMA",
  "La alarma no suena",
  "de caladora",
  "No encienden las luces de niebla",
  "Tengo un chevrolet optra",
  "rotura de semieje trasero duster 4wd",
  "semieje trasero",
  "no gira la llave",
  "prende y de apaga las luces baja",
  "tengo problema con la luces baja prende y se apagan",
  "en la mañana no agarra los cambios",
  "en frio no agarra velocidad",
  "no hace los cambios",
  "motor no hace cambios",
  "no cambia de velocidad",
  "Humo después del lavado de motor",
  "cambia filtro diesel kia sorento",
  "filtro diesel",
  "se",
  "Consumo",
  "cierre",
  "cierre centralizado cristales",
  "computadora",
  "Luz de averia de motor",
  "Consumo de aceite",
  "Radio",
  "Radio#select-com58c35f4683da5411005cc5e7",
  "Mi auto se le activo el paralizador de motor k puedo aser",
  "falla en la mañana",
  "fallas de sensor oxigeno",
  "sensor de oxigeno",
  "tiembla",
  "tiembla sensor",
  "vibra",
  "BOBINA ENCENDIDO",
  "Mazda cx5",
  "cuerpo mariposa",
  "muy acelerada meriva",
  "poco caudal de viento",
  "sensor map",
  "fuga de liga fiesta bala",
  "modulo electroventilador",
  "alternador",
  "testigo del airbag",
  "al prenderlo avienta el agua por el tapon de radiador",
  "Tironeo",
  "Tironeo vento",
  "falla de electroventilador",
  "poner en tiempo el fiat siena",
  "poner en tiempo fiat siena",
  "MI AUTO CASCAVEDEA MUCHO CUANDO PRENDO EL AIRE'",
  "MI AUTO TIEMBLA MUCHO CUANDO PRENDO EL AIRE",
  "Válvula iac",
  "hace un ruido en los inyectores es normal",
  "Alarma",
  "Revoluciones",
  "frena en curva",
  "pita",
  "toyota",
  "toyota previa",
  "30-43le",
  "P0700",
  "jeep cherokee 30-43LE",
  "distribucion",
  "polea de caladora",
  "Cuanto aceite lleva el Civic ex 2008",
  "consumo gasolina",
  "consume  mucho",
  "consume mucha gasolina",
  "consumo  alto",
  "consumo alto de gasolina",
  "consumo de gasolina alto",
  "consumo elevado gasolina",
  "ecu",
  "gasolina",
  "gasolina alta",
  "no enfria",
  "sensor",
  "sensor tps",
  "sensor de ventilacion del tsuru 1994",
  "escaner daewoo matiz",
  "valvulas daewoo matiz",
  "Temperatura a 70 grados",
  "falla electrica provoco que de marcha y no prenda es un cavalier 98 2.2",
  "Chery",
  "Harina 7",
  "Mazda ck7",
  "Captiva pistonea",
  "Captiva sin fuerza",
  "Captva sin fuerza en subida",
  "humo negro",
  "Swift",
  "cambios",
  "transmision",
  "transmision#select-com58d4338cf0058f11007623b0",
  "aire acondicionado",
  "no enciende el aire acondicionado",
  "mi optra no marca la temperatura",
  "mi optra no marca la temperatura cuando sube",
  "orden de encendido ford fiesta 1.6",
  "civic 2012",
  "bomba de gasolina sin retorno",
  "golpea de 2 a 3ra",
  "Problema de aceleracion",
  "no arranca",
  "no arranca",
  "no arranca aunque le heche gasolina al cuerpo de aceleracion",
  "tierra a las bobinas de una una ram 4.7",
  "Sable",
  "Sable 2001",
  "Sensor esp",
  "C0899",
  "Encendido check engine en peugeot 2014",
  "base del filtro de aceite terios",
  "problema con el croche",
  "problema con el croche terios",
  "Vibración en el motor",
  "aire",
  "combustion",
  "falta de chispa en la bobina",
  "moja candelas de combustible",
  "passat no arranca",
  "pastilla",
  "toma de aire",
  "valvula pcv",
  "Frenos rav4 2016",
  "P1737",
  "Batería sonic ltz 2015",
  "Batería sonic ltz 2015#select-com58cef57eb4dd7b10003a50de",
  "Tablero de stratus no marca",
  "01314",
  "P0106",
  "como eliminar mi cuenta",
  "como eliminar mi perfil",
  "eliminar mi cuenta",
  "quitar mi cuenta",
  "quitar mis dato",
  "mi camioneta fort ranger pierde potencia al acelerar y povo a poco va responduendo se apaga sola en frenado brusci o pendientes y en topes y baches se quuere apagar o pierde potencia que sera",
  "mi twingo le cuesta arrancar",
  "araña",
  "parrillas delanteras",
  "porta maza",
  "Cheyenne 2004",
  "ford fiesta se descarga la bateria apagado",
  "potencia  de motor reducida",
  "se descarga la bateria apagado",
  "aguja de temperatura",
  "se ahoga",
  "se ahoga galloper diesel",
  "direccion dura",
  "se subio 2 rayas la temperatura, cascabeleo y se apago",
  "se subio 2 rayas la temperatura, cascabeleo y se apago sentra 2008",
  "diagrama electrico de windstar",
  "testigo de aceite",
  "2012",
  "Problema con el compresor",
  "Sensor de cigüeñal",
  "P1639 ecosport",
  "cuerpo aceleracion ecosport",
  "cuerpo de aceleracion eco sport",
  "p1639",
  "p1639 ecosport",
  "alarma",
  "problemas con aire acondicionado",
  "ELANTRA 2016",
  "FOCUS 2014",
  "FORD FOCUS",
  "208",
  "nivelación de revoluciones",
  "revoluciones",
  "Ubicación válvula egr hyundai elantra 2002",
  "Ubicación válvula ver hyundai delantera 2002",
  "Frenos",
  "Se acelera cada tanto",
  "Slim",
  "Ruido en balatas",
  "Ruido en las balatas recien cambiadas",
  "altima 1999",
  "No tiene fuerza",
  "Se apaga",
  "Se apaga  mi honda odyssey",
  "Se apaga de repente mi Honda Odyssey 2001",
  "No enciende",
  "Encendido luz herramienta",
  "bateria",
  "falla nafta no arranca en frio",
  "Chery tiggo",
  "Problema de velocimetro chery tiggo",
  "Velocimetro chery tiggo funciona a veces",
  "Velocimetro no funciona",
  "yaris hash bag",
  "TXL NO TIENE CORRIENTE",
  "se calienta",
  "servicio ahora dice en el tablero",
  "Darc",
  "Maynar",
  "Suran",
  "Parpadea",
  "Cambio de cubiertas",
  "Cambio de rodado",
  "Calentamiento en un fiesta 2006 motor 1.6",
  "Electroventilador",
  "golpeaaldesacelerar",
  "problemasdbimasa",
  "problemasdeenbrague",
  "ruidoaldesaselerarcomcruseta",
  "Aceite de motor",
  "Tengo una f 150 2009 todo esta aparentemente bien pero de ves en cuando me cancanea como si resbalara la transmision por favor alguien tiene idea de que puede ser",
  "luz de guantera",
  "hola Mi eco es 2005 quisiera saber cuales son las Medidas del PUENTE DELANTERO",
  "hola Mi eco es 2005 quisiera saber cuales son las medidas del puente delantero ya que me esta reventando la Junta Homocinetica",
  "Clutch de jetta a4 raspa y tira aceite",
  "Clutch jetta a4",
  "queda en segunda",
  "Nissan tiida 2015",
  "SENTRA 2011",
  "sentra",
  "sentra 2011",
  "como borrar el codigo de mantenimiento al motor",
  "no arranca town country",
  "si da marcha pero no arrancada",
  "A mi honda odyssey 2004 se le prendio la luz  tcs que significa",
  "2013",
  "CR-V",
  "CRV",
  "Corolla",
  "For focus",
  "Ford Focus",
  "Hond",
  "Honda",
  "Honda CRV 2017",
  "Toyota Rav4",
  "rav4",
  "falla chevrolet colorado",
  "tengo una falla con una chevrolet colorado no llega corriente en tres bobina",
  "Ruido en el motor",
  "Ruido en el motor",
  "falla p0300 p0420",
  "Mi Astra  2005 no acelera de repente  acelera y de repente no no ase cambios  y aveces no agarra la reversa",
  "Mi carro lo ase los cambios",
  "CHAPA JETTA A4",
  "SPARK NG",
  "SPARK NG NO QUIERO EL SATFINDER",
  "mi camioneta le doy vuelta al volante y se apaga",
  "Cambios la caja",
  "Jetta",
  "Jetta automatico a4",
  "No cambia de velocidad jetta automatico",
  "No revoluciona",
  "Se apaga al dar vuelta",
  "Se apaga al girar volante",
  "Los cambios no entran bien",
  "alarma",
  "golpe en parte trasera",
  "humo por donde se le deposita el aceite de motor en un beetle",
  "4x4 parpadea",
  "al acelerar se detiene el motor",
  "que significa el codigo u0009 del hyundai elantra año 2005",
  "Le cuesta trabajo arrancar",
  "No me arranca el coche",
  "No me arranca el coche después de clase",
  "cajuela",
  "Existe fusible para los ventiladores del nissan sentra",
  "Los ventiladores no me encienden",
  "No me encienden los ventiladores",
  "No me funcionan los ventiladores de mi nissan sentra",
  "presión de aceite",
  "Se calienta",
  "Calienta y se apaga",
  "Cuando calienta se apaga",
  "levanta cristales",
  "Alarma de máxima 1999",
  "xsara picasso",
  "Hay dos fichas sueltas",
  "Hay dos fichas sueltas",
  "Bluetooth",
  "Bluetooth golf",
  "Bluetooth moto g",
  "Arranque fiesta",
  "fiat 147",
  "olor a quemado del motor",
  "golf tsi embrague",
  "Mi almera no regula las revoluciones",
  "BOBINAS DE IGNICION",
  "EXPLOSIONES",
  "aire acondicionado",
  "jalonea cambios",
  "BOMBA DE GASOLINA",
  "COMPUTADOR FALLAS",
  "RANGER 1997",
  "RELAY",
  "RELAY BOMBA DE GASOLINA",
  "RELAY DE GASOLINA"
]
